
WEEK_IDX_RANGE = range(1, 14)

DEMOGRAPHICS_VARS = [
    'TBIRTH_YEAR', 'EGENDER', 'MS', 'EST_ST',
    'RHISPANIC', 'RRACE',
    'EEDUC',
    'THHLD_NUMPER', 'THHLD_NUMKID', 'THHLD_NUMADLT',
    'INCOME',
]

HEALTH_VARS = [
    'HLTHSTATUS',
    'ANXIOUS', 'WORRY', 'INTEREST', 'DOWN'
]

WORK_VARS = [
    'WRKLOSS', 'EXPCTLOSS', 'ANYWORK', 'KINDWORK', 'RSNNOWRK', 'UNEMPPAY'
]